# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colin Rowell, PhD
email: crowell@eoas.ubc.ca
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Dr. Colin Rowell, an earth scientist at the University of British Columbia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://colinrr.github.io" # the base hostname & protocol for your site
twitter_username: colin_rowell
github_username:  colinrr

# Build settings
markdown: kramdown
theme: minima
